'use client';
import {useEffect, useState, type FormEvent} from 'react';
import Drawer, {DrawerBackdrop} from '@/app/drawer';
import Link from 'next/link';
type Provider = {key:string;label:string;implemented:boolean;capabilities:string[];fields:{key:string;label:string;secret:boolean}[]};
type Connection = {id:string;name:string;providerKey:string;status:string};
export default function Providers() {
  const [providers,setProviders]=useState<Provider[]>([]),[connections,setConnections]=useState<Connection[]>([]),[selected,setSelected]=useState<Provider|null>(null),[values,setValues]=useState<Record<string,string>>({}),[name,setName]=useState('Default'),[error,setError]=useState(''),[busy,setBusy]=useState(false);
  async function load(){const r=await fetch('/api/v1/providers');if(!r.ok)throw new Error('Unable to load providers');const v=await r.json();setProviders(v.providers);setConnections(v.connections)}
  useEffect(()=>{const controller=new AbortController();fetch('/api/v1/providers',{signal:controller.signal}).then(async r=>{if(!r.ok)throw new Error('Unable to load providers');const v=await r.json();setProviders(v.providers);setConnections(v.connections)}).catch(e=>{if(!controller.signal.aborted)setError(e.message)});return()=>controller.abort()},[]);
  function close(){if(!busy){setSelected(null);setValues({})}}
  async function save(e:FormEvent){e.preventDefault();setBusy(true);setError('');try{const r=await fetch('/api/v1/providers',{method:'POST',headers:{'Content-Type':'application/json'},body:JSON.stringify({providerKey:selected?.key,name,isDefault:true,settings:values})});if(!r.ok)throw new Error((await r.json()).error||'Unable to save');setSelected(null);setValues({});await load()}catch(e){setError(e instanceof Error?e.message:'Unable to save')}finally{setBusy(false)}}
  async function remove(id:string){setError('');try{const r=await fetch('/api/v1/providers',{method:'DELETE',headers:{'Content-Type':'application/json'},body:JSON.stringify({id})});if(!r.ok)throw new Error('Unable to disconnect');await load()}catch(e){setError(e instanceof Error?e.message:'Unable to disconnect')}}
  return <>{error&&!selected&&<p role="alert">{error}</p>}<section className="grid">{providers.map(p=><article className="card g-card" key={p.key}><h2>{p.label}</h2><p>{p.capabilities.join(', ')}</p><p>{p.implemented?'Available':'Adapter implementation pending'}</p><button className="btn button btn-light" onClick={()=>{setSelected(p);setValues({});setName('Default');setError('')}}>Add connection</button></article>)}</section>
    <DrawerBackdrop open={!!selected} onClose={close}/><Drawer open={!!selected} title={`Connect ${selected?.label??'provider'}`} onClose={close}>{selected&&<form className="drawer-form" onSubmit={save}><p>Connections belong to your active organization. Secret fields are encrypted and never displayed again.</p><label>Connection name<input className="form-control" required maxLength={80} value={name} onChange={e=>setName(e.target.value)}/></label>{selected.fields.map(f=><label key={f.key}>{f.label}<input className="form-control" type={f.secret?'password':'text'} autoComplete="off" maxLength={4096} value={values[f.key]??''} onChange={e=>setValues({...values,[f.key]:e.target.value})}/></label>)}{error&&<p role="alert">{error}</p>}<button className="btn button primary btn-primary" disabled={busy}>{busy?'Saving…':'Save connection'}</button><button type="button" className="btn button btn-light" disabled={busy} onClick={close}>Cancel</button></form>}</Drawer>
    <section className="card g-card"><h2>Workspace connections</h2>{!connections.length&&<p>No connections yet. Add a provider above.</p>}{connections.map(c=><article key={c.id}><h3><Link href={`/providers/${encodeURIComponent(c.id)}`}>{c.name} →</Link></h3><p>{c.providerKey}: {c.status} (not a connectivity test)</p><button className="btn button danger btn-danger" onClick={()=>void remove(c.id)}>Disconnect</button></article>)}</section></>;
}
