import{createCipheriv,createDecipheriv,createHash,randomBytes,randomUUID}from'node:crypto';import{DynamoDBClient}from'@aws-sdk/client-dynamodb';import{DynamoDBDocumentClient,GetCommand,PutCommand,QueryCommand,DeleteCommand}from'@aws-sdk/lib-dynamodb';import{store}from'./store';
export type Provider={key:string;label:string;capabilities:string[];implemented:boolean;fields:{key:string;label:string;secret:boolean}[]};
export const providers:Provider[]=[{key:'ring',label:'Ring',capabilities:['device-discovery','signed-webhooks','recorded-snapshots'],implemented:true,fields:[{key:'clientId',label:'OAuth client ID',secret:false},{key:'clientSecret',label:'OAuth client secret',secret:true},{key:'accountId',label:'Linked Ring account ID',secret:false},{key:'accessToken',label:'Staging / linked-account access token',secret:true},{key:'hmacKey',label:'Webhook HMAC signing key',secret:true}]},{key:'firetv',label:'Fire TV',capabilities:['read-only-display','device-pairing'],implemented:true,fields:[{key:'applicationId',label:'Application ID',secret:false}]},{key:'alexa',label:'Alexa+',capabilities:['voice','incident-query'],implemented:false,fields:[{key:'skillId',label:'Skill ID',secret:false},{key:'clientSecret',label:'Client secret',secret:true}]},{key:'bedrock',label:'Amazon Bedrock',capabilities:['incident-summary'],implemented:false,fields:[{key:'modelId',label:'Model or inference profile ID',secret:false}]}];
export type ProviderSetting={id:string;orgId:string;userId:string;providerKey:string;name:string;isDefault:boolean;enabled:boolean;settings:Record<string,string>;createdAt:string;updatedAt:string};
const table=process.env.SMARTDETECTOR_TABLE,db=DynamoDBDocumentClient.from(new DynamoDBClient({endpoint:process.env.SMARTDETECTOR_DYNAMODB_ENDPOINT})),memory=new Map<string,ProviderSetting>();
function encryptionKey(){const s=process.env.SMARTDETECTOR_PROVIDER_SECRET||process.env.SMARTDETECTOR_SESSION_SECRET;if(!s||s.length<32)throw new Error('Provider encryption secret is required');return createHash('sha256').update(s).digest()}
export function encryptSecret(value:string,scope:string){const iv=randomBytes(12),c=createCipheriv('aes-256-gcm',encryptionKey(),iv);c.setAAD(Buffer.from(scope));return['enc',iv.toString('hex'),Buffer.concat([c.update(value,'utf8'),c.final()]).toString('hex'),c.getAuthTag().toString('hex')].join(':')}
export function decryptSecret(value:string,scope:string){const[,iv,body,tag]=value.split(':');const c=createDecipheriv('aes-256-gcm',encryptionKey(),Buffer.from(iv,'hex'));c.setAAD(Buffer.from(scope));c.setAuthTag(Buffer.from(tag,'hex'));return Buffer.concat([c.update(Buffer.from(body,'hex')),c.final()]).toString('utf8')}
export async function listSettings(orgId:string):Promise<ProviderSetting[]>{await store.organizationById(orgId);if(table){const r=await db.send(new QueryCommand({TableName:table,KeyConditionExpression:'pk=:pk AND begins_with(sk,:prefix)',ExpressionAttributeValues:{':pk':'ORG#'+orgId,':prefix':'PROVIDER#'},ConsistentRead:true}));return(r.Items??[])as ProviderSetting[]}return[...memory.values()].filter(v=>v.orgId===orgId)}
export async function setting(orgId:string,id:string):Promise<ProviderSetting|null>{if(table){const r=await db.send(new GetCommand({TableName:table,Key:{pk:'ORG#'+orgId,sk:'PROVIDER#'+id},ConsistentRead:true}));return(r.Item as ProviderSetting)??null}const v=memory.get(id);return v?.orgId===orgId?v:null}
export function publicSetting(v:ProviderSetting){const provider=providers.find(p=>p.key===v.providerKey);return{...v,status:!v.enabled?'disabled':provider?.implemented?'configured':'setup_required',settings:Object.fromEntries(Object.entries(v.settings).map(([k,value])=>[k,provider?.fields.find(f=>f.key===k)?.secret?(value?'configured':''):value]))}}
export async function saveSetting(orgId:string,userId:string,input:{id?:string;providerKey:string;name:string;isDefault?:boolean;enabled?:boolean;settings:Record<string,string>}){const p=providers.find(p=>p.key===input.providerKey);if(!p||!input.name?.trim()||input.name.length>80||!input.settings||typeof input.settings!=='object')throw new Error('Invalid provider connection');const existing=input.id?await setting(orgId,input.id):null;if(input.id&&!existing)throw new Error('Connection not found');if(existing&&existing.providerKey!==p.key)throw new Error('Provider cannot be changed');const id=existing?.id??randomUUID(),settings={...existing?.settings};for(const f of p.fields){const value=input.settings[f.key];if(value===undefined||value==='')continue;if(typeof value!=='string'||value.length>4096)throw new Error('Invalid provider field');settings[f.key]=f.secret?encryptSecret(value,orgId+':'+id+':'+f.key):value}const v:ProviderSetting={id,orgId,userId,providerKey:p.key,name:input.name.trim(),isDefault:input.isDefault??true,enabled:input.enabled??true,settings,createdAt:existing?.createdAt??new Date().toISOString(),updatedAt:new Date().toISOString()};if(table)await db.send(new PutCommand({TableName:table,Item:{pk:'ORG#'+orgId,sk:'PROVIDER#'+id,...v}}));else memory.set(id,v);return v}
export async function removeSetting(orgId:string,id:string){if(!await setting(orgId,id))return false;if(table)await db.send(new DeleteCommand({TableName:table,Key:{pk:'ORG#'+orgId,sk:'PROVIDER#'+id}}));else memory.delete(id);return true}
export async function credentials(orgId:string,key:string){const rows=(await listSettings(orgId)).filter(v=>v.providerKey===key&&v.enabled).sort((a,b)=>Number(b.isDefault)-Number(a.isDefault)||b.updatedAt.localeCompare(a.updatedAt));const v=rows[0],p=providers.find(v=>v.key===key);if(!v||!p)return null;return Object.fromEntries(Object.entries(v.settings).map(([k,value])=>[k,p.fields.find(f=>f.key===k)?.secret?decryptSecret(value,orgId+':'+v.id+':'+k):value]))}



export async function connectionCredentials(orgId:string,id:string,providerKey:string){const v=await setting(orgId,id),p=providers.find(p=>p.key===providerKey);if(!v||!v.enabled||v.providerKey!==providerKey||!p)return null;return Object.fromEntries(Object.entries(v.settings).map(([k,value])=>[k,p.fields.find(f=>f.key===k)?.secret?decryptSecret(value,orgId+":"+v.id+":"+k):value]));}


