'use client';
import {useEffect,useState} from 'react';
import Link from 'next/link';
import CameraMedia from '../../camera-media';
import {eventView} from '@/lib/event-view';
type Device={serverId:string;displayName:string;providerKey?:string;status:string;lastHeartbeat:string};
type Event={incidentId:string;serverId:string;startedAt:string;state:string;payload:unknown};
export default function DeviceDetail({deviceId}:{deviceId:string}){
 const [device,setDevice]=useState<Device|null>(null),[events,setEvents]=useState<Event[]>([]),[error,setError]=useState('');
 useEffect(()=>{const controller=new AbortController();let busy=false;async function load(){if(busy)return;busy=true;try{const [d,e]=await Promise.all([fetch('/api/v1/devices/'+encodeURIComponent(deviceId),{signal:controller.signal}),fetch('/api/v1/incidents',{signal:controller.signal})]);if(!d.ok||!e.ok)throw Error('Device unavailable in this location, or access has expired.');const node=await d.json(),rows:Event[]=await e.json();if(!controller.signal.aborted){setDevice(node);setEvents(rows.filter(r=>r.serverId===deviceId));setError('')}}catch(e){if(!controller.signal.aborted)setError(e instanceof Error?e.message:'Unable to load device')}finally{busy=false}}void load();const timer=setInterval(()=>void load(),5000);return()=>{controller.abort();clearInterval(timer)}},[deviceId]);
 const latest=events[0],view=latest?eventView(latest.payload):null;
 return <><section className="hero"><div className="d-flex gap-3"><Link href="/console">← Dashboard</Link><Link href="/devices">Devices</Link></div><p className="eyebrow mt-3">Device review</p><h1>{device?.displayName??'Device'}</h1><p className="muted">Your active location · {device?.providerKey??'Connected device'} · {device?.status??'Loading…'}</p>{error&&<p className="alert alert-danger" role="alert">{error}</p>}</section>{device&&<div className="row g-4"><aside className="col-lg-4"><section className="card g-card h-100"><h2 className="h4">Recent device events</h2><p className="small text-muted">Updates every five seconds. Events from the location’s 50 most recent records.</p>{events.length?<div className="list-group list-group-flush">{events.map(event=>{const v=eventView(event.payload);return <Link key={event.incidentId} href={'/events/'+encodeURIComponent(event.incidentId)+'?device='+encodeURIComponent(deviceId)} className="list-group-item list-group-item-action px-0 py-3"><div className="d-flex gap-3 align-items-center">{v.preview&&<img src={v.preview} alt="Event thumbnail" width={88} height={50} style={{objectFit:'cover',borderRadius:6}}/>}<div><strong className="d-block text-capitalize">{v.kind}</strong><time className="small text-muted" dateTime={event.startedAt}>{new Date(event.startedAt).toLocaleString()}</time><span className="small d-block">Review event →</span></div></div></Link>})}</div>:<p>No events received for this device yet.</p>}</section></aside><section className="col-lg-8"><div className="card overflow-hidden">{device.providerKey==='ring'?<CameraMedia id={deviceId} name={device.displayName} eventPreview={view?.preview} detections={view?.evidenceFrames[0]?.detections} large/>:<div className="card-body"><h2 className="h4">Device activity</h2><p>Latest reported status: {device.status}</p></div>}</div><div className="card g-card mt-4"><h2 className="h4">Camera observations</h2><p>{view?.aiSummary||'Select an event to review its observations and AI context.'}</p><p className="small text-muted mb-0">Stored image, not continuous live video. Live view starts only when you request it. AI interpretations are advisory.</p>{latest&&<Link className="btn btn-outline-primary align-self-start mt-3" href={'/events/'+encodeURIComponent(latest.incidentId)+'?device='+encodeURIComponent(deviceId)}>Review latest event →</Link>}</div></section></div>}</>;
}
