import{test}from'node:test';import assert from'node:assert/strict';import{alarm,validSignal,ingest}from'../src/lib/signals';import{store}from'../src/lib/store';import{createSession,verifySession}from'../src/lib/session';
test('deterministic alarm and invalid readings',()=>{assert.equal(alarm({device_id:'demo',type:'smoke',value:49}),false);assert.equal(alarm({device_id:'demo',type:'smoke',value:50}),true);assert.equal(validSignal({device_id:'demo',type:'smoke',value:NaN}),false)});
test('signals and incidents remain isolated by organization',async()=>{const a=await store.createOrganization({name:'Synthetic A',ownerId:'test',orgType:'business'}),b=await store.createOrganization({name:'Synthetic B',ownerId:'test',orgType:'business'});await ingest(a.id,'test',{device_id:'demo',type:'smoke',value:80,event_id:'repeatable'});await ingest(a.id,'test',{device_id:'demo',type:'smoke',value:80,event_id:'repeatable'});assert.equal((await store.incidents(a.id)).length,1);assert.equal((await store.incidents(b.id)).length,0)});
test('session signature rejects tampering',async()=>{const s=await createSession({id:'test',username:'synthetic',role:'admin',orgId:'demo',expiresAt:Date.now()+60000},'a'.repeat(32));assert.ok(await verifySession(s,'a'.repeat(32)));assert.equal(await verifySession(s+'tampered','a'.repeat(32)),null)});


import{encryptSecret,decryptSecret,saveSetting,listSettings,publicSetting,credentials}from'../src/lib/providers';
test('provider credentials are encrypted, redacted, and tenant isolated',async()=>{process.env.SMARTDETECTOR_SESSION_SECRET='synthetic-test-secret-32-characters-long';const a=await store.createOrganization({name:'Provider Synthetic A',ownerId:'test',orgType:'business'}),b=await store.createOrganization({name:'Provider Synthetic B',ownerId:'test',orgType:'business'});const v=await saveSetting(a.id,'test',{providerKey:'autovision',name:'Demo',settings:{apiKey:'synthetic-secret'}});assert.notEqual(v.settings.apiKey,'synthetic-secret');assert.equal(publicSetting(v).settings.apiKey,'configured');assert.equal((await credentials(a.id,'autovision'))?.apiKey,'synthetic-secret');assert.equal((await listSettings(b.id)).length,0);const encrypted=encryptSecret('value','tenant-a');assert.throws(()=>decryptSecret(encrypted,'tenant-b'))});

