import {test} from 'node:test';
import assert from 'node:assert/strict';
import {createHmac} from 'node:crypto';
import {store} from '../src/lib/store';
import {saveSetting,publicSetting,connectionCredentials,setting} from '../src/lib/providers';
import {receiveRingCode,completeRingLink,validRingNonce,ringAccess} from '../src/lib/ring-link';
import {connectRingDevice} from '../src/lib/device-connect';
import {ingest} from '../src/lib/signals';
import {NextRequest} from 'next/server';
import {POST as linkRoute} from '../src/app/api/v1/integrations/ring/link/route';
import {createSession,sessionCookie} from '../src/lib/session';
const hmacKey='synthetic-ring-signing-key';
const nonce=(time:string,account='synthetic-ring-account')=>createHmac('sha256',hmacKey).update(time+':'+account).digest('base64url');
const reply=(value:unknown,status=200)=>new Response(JSON.stringify(value),{status,headers:{'Content-Type':'application/json'}});
test('Ring nonce rejects expiration, future time, tampering, and wrong accounts',()=>{const now=Date.now(),time=String(now);assert.equal(validRingNonce(nonce(time),time,'synthetic-ring-account',hmacKey,now),true);assert.equal(validRingNonce(nonce(time),time,'other-account',hmacKey,now),false);assert.equal(validRingNonce(nonce(time),time,'synthetic-ring-account',hmacKey,now+600001),false);assert.equal(validRingNonce(nonce(time),time,'synthetic-ring-account',hmacKey,now-1),false);assert.equal(validRingNonce('bad',time,'synthetic-ring-account',hmacKey,now),false)});
test('Ring linking encrypts tokens, binds location and nonce, completes POST/PATCH, and rejects replay',async()=>{
 process.env.SMARTDETECTOR_SESSION_SECRET='synthetic-ring-session-secret-long-enough';
 const org=await store.createOrganization({name:'Synthetic Ring Location',ownerId:'test',orgType:'business'}),other=await store.createOrganization({name:'Synthetic Other Location',ownerId:'test',orgType:'business'});
 const c=await saveSetting(org.id,'test',{providerKey:'ring',name:'Synthetic camera account',settings:{clientId:'synthetic-client',clientSecret:'synthetic-client-secret',hmacKey}});
 const calls:string[]=[];
 const mock=(async(url:RequestInfo|URL,init?:RequestInit)=>{const u=String(url);calls.push((init?.method??'GET')+' '+u);if(u.includes('oauth/token'))return reply({access_token:'synthetic-access',refresh_token:'synthetic-refresh',expires_in:14400});if(u.endsWith('/users/me'))return reply({data:{id:'synthetic-ring-account'}});return reply({data:{attributes:{status:'completed'}}});})as typeof fetch;
 assert.deepEqual(await receiveRingCode(org.id,c.id,'synthetic-code',mock),{accepted:true});
 assert.equal((await connectionCredentials(org.id,c.id,'ring'))?.accessToken,undefined);
 const time=String(Date.now());
 await assert.rejects(completeRingLink(other.id,c.id,'test',nonce(time),time,mock));
 await assert.rejects(completeRingLink(org.id,c.id,'test',nonce(time,'wrong'),time,mock));
 assert.deepEqual(await completeRingLink(org.id,c.id,'test',nonce(time),time,mock),{linked:true});
 assert.equal((await connectionCredentials(org.id,c.id,'ring'))?.accessToken,'synthetic-access');
 const saved=(await setting(org.id,c.id))!;assert.notEqual(saved.settings.refreshToken,'synthetic-refresh');assert.equal(publicSetting(saved).settings.refreshToken,'configured');
 assert.ok(calls.some(c=>c.startsWith('POST https://api.amazonvision.com')));assert.ok(calls.some(c=>c.startsWith('PATCH https://api.amazonvision.com')));
 await assert.rejects(completeRingLink(org.id,c.id,'test',nonce(time),time,mock));
 const discovery=(async()=>reply({data:[{id:'synthetic-camera',attributes:{name:'Synthetic porch'},relationships:{capabilities:{data:{id:'synthetic-caps'}}}},{id:'synthetic-sensor',attributes:{name:'Synthetic sensor'}}],included:[{id:'synthetic-caps',type:'device-capabilities',attributes:{video:{codecs:['AVC']}}}]}))as typeof fetch;
 await assert.rejects(connectRingDevice(org.id,c.id,'ring-doorbell','synthetic-sensor',discovery));
 await assert.rejects(connectRingDevice(org.id,c.id,'ring-doorbell','unshared-camera',discovery));
 await assert.rejects(connectRingDevice(other.id,c.id,'ring-doorbell','synthetic-camera',discovery));
 const device=await connectRingDevice(org.id,c.id,'ring-doorbell','synthetic-camera',discovery);
 assert.equal((await store.node(org.id,device.serverId))?.status,'pending');
 await ingest(org.id,'ring',{device_id:device.serverId,type:'motion',value:1});
 assert.equal((await store.node(org.id,device.serverId))?.connectionId,c.id);assert.equal((await store.node(org.id,device.serverId))?.displayName,'Synthetic porch');
 await saveSetting(org.id,'test',{id:c.id,providerKey:'ring',name:c.name,settings:{expiresAt:'1'}});
 assert.equal((await ringAccess(org.id,c.id,mock)).accessToken,'synthetic-access');
});
test('Ring account claiming requires admin login, same-origin, and matching location',async()=>{
 const secret=process.env.SMARTDETECTOR_SESSION_SECRET='synthetic-ring-session-secret-long-enough';
 const cookie=await createSession({id:'root',username:'root',role:'root',orgId:'synthetic-location',expiresAt:Date.now()+60000},secret);
 const request=(origin:string,orgId:string)=>new NextRequest('https://test.example/api/v1/integrations/ring/link',{method:'POST',headers:{host:'test.example',origin,cookie:sessionCookie+'='+cookie,'Content-Type':'application/json'},body:JSON.stringify({orgId,connectionId:'synthetic-connection',nonce:'synthetic',time:String(Date.now())})});
 assert.equal((await linkRoute(request('https://foreign.example','synthetic-location'))).status,403);
 assert.equal((await linkRoute(request('https://test.example','other-location'))).status,403);
 assert.equal((await linkRoute(new NextRequest('https://test.example/api/v1/integrations/ring/link',{method:'POST'}))).status,403);
});
