'use client';
import {useState} from 'react';
import Link from 'next/link';
export default function ConnectDisplay() {
  const [code,setCode] = useState(''), [pair,setPair] = useState<{name:string;orgId:string;orgName:string}|null>(null), [message,setMessage] = useState(''),[busy,setBusy]=useState(false),[connected,setConnected]=useState(false);
  async function inspect(){setBusy(true);setPair(null);setMessage('');setConnected(false);try{const r=await fetch('/api/v1/tv/approve?code='+encodeURIComponent(code),{cache:'no-store'}),v=await r.json();if(!r.ok)throw Error(v.error);setPair(v)}catch(e){setMessage(e instanceof Error?e.message:'Unable to check code')}finally{setBusy(false)}}
  async function approve(){setBusy(true);try{const r=await fetch('/api/v1/tv/approve',{method:'POST',headers:{'Content-Type':'application/json'},body:JSON.stringify({code,orgId:pair?.orgId})}),v=await r.json();if(!r.ok)throw Error(v.error);setMessage('Display connected. Return to your TV.');setConnected(true);setPair(null);setCode('')}catch(e){setMessage(e instanceof Error?e.message:'Unable to approve display')}finally{setBusy(false)}}
  return <><section className="hero"><Link href="/devices/integrations/firetv">← Fire TV</Link><h1>Connect your TV</h1><p className="muted">Pair a read-only display with your active location. Only administrators can approve a display.</p></section><div className="row g-4"><section className="col-12 col-lg-7"><div className="card g-card vstack gap-3"><h2 className="h4">Enter the pairing code</h2><form className="vstack gap-3" onSubmit={e=>{e.preventDefault();void inspect()}}><label htmlFor="tv-code" className="form-label mb-0">Code shown on TV</label><input id="tv-code" className="form-control form-control-lg font-monospace" value={code} disabled={busy} onChange={e=>{setCode(e.target.value.toUpperCase());setPair(null);}} maxLength={11} autoComplete="off" required placeholder="XXXX-XXXX"/><button className="btn btn-primary align-self-start" disabled={busy||!code.trim()}>{busy?'Checking…':'Check code'}</button></form>{pair&&<section className="border rounded-3 p-3 vstack gap-3"><h3 className="h5 mb-0">Approve {pair.name}?</h3><p className="mb-0">Location: <strong>{pair.orgName}</strong></p><p className="muted mb-0">Grants read-only access to event summaries and previews for 24 hours. Approve only a code visible on your own display.</p><button className="btn btn-primary align-self-start" disabled={busy} onClick={()=>void approve()}>{busy?'Approving…':'Approve this display'}</button></section>}{message&&<div role="status" className={`alert ${connected?'alert-success':'alert-warning'} mb-0`}>{message}{connected&&<Link className="d-block mt-2" href="/devices/integrations/firetv">View your Fire TV connections →</Link>}</div>}</div></section><aside className="col-12 col-lg-5"><div className="card g-card"><h2 className="h4">On your Fire TV</h2><ol className="ps-3 mb-3"><li>Open the SmartDetector TV app and choose Get pairing code.</li><li>Enter that code here and confirm the intended location.</li><li>Return to the TV to view your event feed.</li></ol><p className="muted">For a local browser preview, <Link href="/tv" target="_blank" rel="noopener noreferrer">open the TV display ↗</Link>. A browser preview is not a substitute for testing on Fire TV.</p><p className="muted mb-0">To revoke access, open Devices → Fire TV → View connection → Disconnect display. No password is stored on the TV.</p></div></aside></div></>;
}
