'use client';
import {useEffect,useState} from 'react';
import Link from 'next/link';
import DetectionImage from './detection-image';
export default function CameraMedia({id,name,eventPreview,detections,large=false}:{id:string;name:string;eventPreview?:string;eventId?:string;detections?:unknown;large?:boolean}){
 const [image,setImage]=useState(''),[busy,setBusy]=useState(false),[message,setMessage]=useState(''),[retrieved,setRetrieved]=useState('');
 async function refresh(signal?:AbortSignal){setBusy(true);setMessage('Requesting latest available image…');try{const r=await fetch('/api/v1/devices/'+encodeURIComponent(id)+'/media',{method:'POST',headers:{'Content-Type':'application/json'},body:JSON.stringify({action:'snapshot'}),signal}),v=await r.json();if(!r.ok)throw Error(v.error);if(!signal?.aborted){setImage(v.image);setRetrieved(v.retrievedAt);setMessage('Latest stored image · not live')}}catch(e){if(!signal?.aborted)setMessage(e instanceof Error?e.message:'Snapshot unavailable')}finally{if(!signal?.aborted)setBusy(false)}}
 useEffect(()=>{if(eventPreview)return;const controller=new AbortController();void refresh(controller.signal);return()=>controller.abort()},[id,eventPreview]);
 const preview=image||eventPreview;
 return <><Link className="device-feed-preview" style={large?{aspectRatio:'16/9',height:'auto',minHeight:240}:undefined} href={'/devices/'+encodeURIComponent(id)} aria-label={'View device '+name}>{preview?<DetectionImage src={preview} alt={'Available image from '+name} detections={image?undefined:detections}/>:<div className="device-feed-empty"><span aria-hidden="true">▣</span><strong>{busy?'Loading latest image…':'No image available yet'}</strong><small>Ring must have accessible stored media.</small></div>}{retrieved&&<span className="device-feed-time">Image retrieved {new Date(retrieved).toLocaleTimeString()} · not live</span>}</Link><div className="p-3 border-top"><div className="d-flex flex-wrap gap-2"><Link className="btn btn-sm btn-primary" href={'/devices/'+encodeURIComponent(id)+'/live'}>Live view</Link><button className="btn btn-sm btn-outline-primary" disabled={busy} onClick={()=>void refresh()}>{busy?'Loading…':'Refresh image'}</button></div>{message&&<p className="small text-muted mt-2 mb-0" role="status">{message}</p>}</div></>;
}
