'use client';
import Link from 'next/link';
import Image from 'next/image';
import CameraMedia from './camera-media';
import {deviceGroup,latestDeviceEvent,type FeedDevice,type FeedEvent} from '@/lib/device-feed';
import {eventView} from '@/lib/event-view';
export default function DeviceFeed({devices,events,loaded}:{devices:FeedDevice[];events:FeedEvent[];loaded:boolean}){
 const groups=['Cameras','TV displays','Sensors & other devices'];
 return <section className="device-feed"><div className="section-heading"><div><h2>Device activity</h2><p className="muted">Updates every five seconds · images show available stored media; use Live view for a live session.</p></div><Link className="btn btn-outline-primary" href="/devices">Connect device</Link></div>{!devices.length?<div className="g-card empty-state"><strong>{loaded?'No connected devices yet':'Loading devices…'}</strong><span>Your authorized devices and event snapshots will appear here.</span></div>:groups.map(group=>{const items=devices.filter(d=>deviceGroup(d)===group);if(!items.length)return null;return <section className="device-feed-group" key={group}><h3>{group}<span>{items.length}</span></h3><div className="device-feed-grid">{items.map(device=>{const event=latestDeviceEvent(events,device.serverId),view=event?eventView(event.payload):null;return <article className="device-feed-card" key={device.serverId}><header><Link href={`/devices/${encodeURIComponent(device.serverId)}`}><span aria-hidden="true">{group==='Cameras'?'▣':group==='TV displays'?'▤':'◈'}</span>{device.displayName}</Link><Link href={`/devices/${encodeURIComponent(device.serverId)}`} aria-label={`Settings for ${device.displayName}`}>⚙</Link></header>{device.providerKey==='ring'?<CameraMedia id={device.serverId} name={device.displayName} eventPreview={view?.preview??undefined} detections={view?.evidenceFrames[0]?.detections} eventId={event?.incidentId}/>:<Link className="device-feed-preview" href={event?`/events/${encodeURIComponent(event.incidentId)}`:`/devices/${encodeURIComponent(device.serverId)}`} aria-label={event?`Review latest event from ${device.displayName}`:`View ${device.displayName}`}>{view?.preview?<Image src={view.preview} alt={`Latest event from ${device.displayName}`} fill unoptimized sizes="(max-width:700px) 100vw, 33vw"/>:<div className="device-feed-empty"><span aria-hidden="true">{group==='Cameras'?'▣':'◈'}</span><strong>{group==='Cameras'?'Awaiting event snapshot':'Awaiting device activity'}</strong><small>No live video stream is active.</small></div>}{event&&<span className="device-feed-time">{view?.synthetic?'Synthetic · ':''}<time dateTime={event.startedAt}>{new Date(event.startedAt).toLocaleString()}</time></span>}</Link>}<footer><span className="status neutral">{device.status==='pending'&&device.providerKey==='ring'?'Connected · awaiting first event':device.status}</span><span className="muted small">{event?'Latest event':'No events received'}</span></footer></article>})}</div></section>})}</section>;
}
