import {cookies} from 'next/headers';
import {redirect} from 'next/navigation';
import {sessionCookie,verifySession} from '@/lib/session';
import Vision from '../settings/autovision';
export default async function Admin(){
 const session=await verifySession((await cookies()).get(sessionCookie)?.value,process.env.SMARTDETECTOR_SESSION_SECRET??'');
 if(!session)redirect('/login');
 if(session.role!=='root')redirect('/settings');
 return <><section className="hero"><p className="eyebrow">Root administration</p><h1>Admin</h1><p>System-wide service configuration and provider setup guidance. Location accounts, cameras, pairing, and event history are managed separately under Devices.</p></section><Vision/><section className="card g-card mb-4"><h2 className="h4">Provider setup instructions</h2><h3 className="h5">Ring</h3><p>Create an app in the <a href="https://developer.amazon.com/ring/console/apps" target="_blank" rel="noreferrer">Ring Developer Console ↗</a>. Configure camera and media scopes. Ring app credentials and callback routing are still stored with existing location connections. A global developer-app configuration migration is required before those settings can be managed here safely. Existing links are preserved. Users launch SmartDetector from the Ring app and confirm their destination location; shared cameras sync into that location after linking.</p><h3 className="h5">Fire TV</h3><p>No customer API credentials are needed. Open <a href="/tv" target="_blank" rel="noreferrer">SmartDetector Console ↗</a> and select Get pairing code. Approve it under Devices → Fire TV → Connect provider. Browser preview is not an Appstore installation. Packaging and background notifications require native Fire TV development and device validation.</p><h3 className="h5">Amazon Bedrock</h3><p>Use CloudFormation deployment settings for the model, region, and least-privilege task-role permissions. Do not enter AWS access keys in customer connections. Per-location Bedrock providers are not implemented.</p><h3 className="h5">Alexa+</h3><p>Planned only; skill linking and voice commands are not yet available. Do not configure it as a working provider.</p></section></>;
}
