"use client";
import {useCallback, useEffect, useRef, useState} from "react";
import "./tv.css";
type Item = {id: string; deviceId: string; state: string; at: string; source: string; thumbnail?: string; summary: string};
type Feed = {updatedAt: string; devices: {id: string; name: string; status: string}[]; incidents: Item[]};
export default function TvClient() {
  const [origin, setOrigin] = useState(""), [token, setToken] = useState(""), [pair, setPair] = useState<{userCode:string;deviceCode:string;expiresAt:number}|null>(null), [feed, setFeed] = useState<Feed | null>(null), [error, setError] = useState(""), [selected, setSelected] = useState<Item | null>(null);
  async function startPairing() {try {const r = await fetch('/api/v1/tv/pair', {method:'POST',headers:{'Content-Type':'application/json'},body:JSON.stringify({name:'Fire TV display'})}); if (!r.ok) throw new Error('Unable to start pairing'); setPair(await r.json());setError('');} catch {setError('Pairing unavailable. Try again.');}}
  useEffect(() => {if (!pair || token) return; const timer = setInterval(async () => {if (Date.now() >= pair.expiresAt) {setPair(null);setError('Code expired. Request a new code.');return;} try {const r = await fetch('/api/v1/tv/pair', {method:'POST',headers:{'Content-Type':'application/json'},body:JSON.stringify({deviceCode:pair.deviceCode})});const v = await r.json();if (v.token) {sessionStorage.setItem('smartdetector-tv',v.token);setToken(v.token);setPair(null);setError('');}} catch {setError('Waiting for service connection…');}},5000);return () => clearInterval(timer);},[pair,token]);
  const root = useRef<HTMLDivElement>(null);
  useEffect(() => {const startup = setTimeout(() => {setOrigin(window.location.origin);const fragment = new URLSearchParams(window.location.hash.slice(1)), value = fragment.get("token") || sessionStorage.getItem("smartdetector-tv") || ""; if (fragment.has("token")) history.replaceState(null,"",window.location.pathname); setToken(value); if (value) sessionStorage.setItem("smartdetector-tv",value);}, 0); return () => clearTimeout(startup);}, []);
  const refresh = useCallback(async () => {if (!token || document.hidden) return;try {const r = await fetch("/api/v1/tv/feed", {headers: {Authorization: "Bearer " + token}, cache: "no-store"}); if (!r.ok) {setFeed(null); throw new Error("Display access expired, revoked, or unavailable. Disconnect and pair this display again.");} setFeed(await r.json()); setError("");} catch (e) {setError(e instanceof Error ? e.message : "Service unavailable");}}, [token]);
  useEffect(() => {const initial = setTimeout(() => void refresh(), 0); const timer = setInterval(() => void refresh(), 5000); return () => {clearTimeout(initial);clearInterval(timer);};}, [refresh]);
  useEffect(() => {const first = root.current?.querySelector<HTMLElement>("button"); first?.focus();}, [token, selected]);
  useEffect(() => {const handle = (e: KeyboardEvent) => {if (e.key === "Escape" || e.key === "BrowserBack" || e.keyCode === 461 || e.key === "Backspace" && !(e.target instanceof HTMLInputElement)) {e.preventDefault();setSelected(null);return;} if (!["ArrowUp","ArrowDown","ArrowLeft","ArrowRight"].includes(e.key) || e.target instanceof HTMLInputElement) return; const buttons = Array.from(root.current?.querySelectorAll<HTMLButtonElement>("button") || []), index = buttons.indexOf(document.activeElement as HTMLButtonElement); if (!buttons.length) return; e.preventDefault(); const step = e.key === "ArrowUp" || e.key === "ArrowLeft" ? -1 : 1; buttons[(index + step + buttons.length) % buttons.length].focus();}; window.addEventListener("keydown",handle);return () => window.removeEventListener("keydown",handle);}, []);
  function disconnect() {sessionStorage.removeItem("smartdetector-tv");setToken("");setFeed(null);setSelected(null);setPair(null);setError("");}
  return <div className="tv-app" ref={root}><header><div><span className="tv-eyebrow">SMARTDETECTOR · FIRE TV DISPLAY</span><h1>See what needs your attention.</h1></div><div><button onClick={() => void refresh()}>Refresh</button>{token && <button onClick={disconnect}>Disconnect</button>}</div></header>{!token ? <section className="tv-connect"><h2>Connect this display</h2><p>On your phone or computer, sign in with your normal SmartDetector account at <strong>{origin}/tv/connect</strong>. Select your organization and approve the code shown below.</p>{pair ? <><h2 style={{fontFamily:'monospace',fontSize:64}}>{pair.userCode}</h2><p>Waiting for approval. This code expires in ten minutes.</p></> : <button onClick={() => void startPairing()}>Get pairing code</button>}<p>No Ring credentials, AutoVision key or root password is stored on the TV.</p></section> : selected ? <section className="tv-detail"><button onClick={() => setSelected(null)}>← Back to activity</button>{selected.thumbnail && <img alt="Analyzed image preview" src={"data:image/jpeg;base64," + selected.thumbnail}/>}<div><span className="tv-eyebrow">{selected.source} · {selected.state}</span><h2>{selected.summary}</h2><p>{new Date(selected.at).toLocaleString()}</p><p>AI observations are advisory. This display cannot issue commands or change alarms.</p></div></section> : <><section className="tv-stats"><span>{feed?.devices.length || 0} connected devices</span><span>{feed?.incidents.length || 0} recent observations</span><span>{feed ? "Updated " + new Date(feed.updatedAt).toLocaleTimeString() : "Connecting…"}</span></section><section className="tv-grid">{feed?.incidents.map(i => <button className="tv-card" key={i.id} onClick={() => setSelected(i)}>{i.thumbnail ? <img src={"data:image/jpeg;base64," + i.thumbnail} alt="Analysis preview"/> : <div className="tv-placeholder">◉</div>}<span className="tv-eyebrow">{i.source} · {i.state}</span><h2>{i.summary}</h2><small>{new Date(i.at).toLocaleString()}</small></button>)}</section>{feed && !feed.incidents.length && <section className="tv-connect"><h2>All quiet for now.</h2><p>Ring observations and service incidents will appear here automatically.</p></section>}</>}{error && <p role="alert" className="tv-error">{error}</p>}<footer>Use the remote arrows and Select. Back returns to activity. Read-only updates every five seconds.</footer></div>;
}
