"use client";
import {useCallback,useEffect,useRef,useState} from 'react';
import Brand from '../brand';
import LiveCamera from '../live-camera';
import DetectionImage from '../detection-image';
import type {ObjectDetection} from '@/lib/object-detections';
import './tv.css';
type Frame={at_ms:number;preview:string;detections?:ObjectDetection[]};
type Item={id:string;deviceId:string;state:string;at:string;source:string;thumbnail?:string;summary:string;frames?:Frame[]};
type Feed={updatedAt:string;devices:{id:string;name:string;status:string;liveView?:boolean}[];incidents:Item[]};
export default function TvClient(){
 const [origin,setOrigin]=useState(''),[token,setToken]=useState(''),[pair,setPair]=useState<{userCode:string;deviceCode:string;expiresAt:number}|null>(null),[feed,setFeed]=useState<Feed|null>(null),[error,setError]=useState(''),[selectedId,setSelectedId]=useState(''),[deviceId,setDeviceId]=useState(''),[frame,setFrame]=useState(0),[live,setLive]=useState(false),[query,setQuery]=useState(''),[alerts,setAlerts]=useState(true),[notice,setNotice]=useState<Item|null>(null);
 const root=useRef<HTMLDivElement>(null),seen=useRef<Set<string>|null>(null),pendingEvent=useRef<string|null>(null),loading=useRef(false);
 const selected=feed?.incidents.find(i=>i.id===selectedId),device=feed?.devices.find(d=>d.id===deviceId);
 const events=(feed?.incidents??[]).filter(i=>(!deviceId||i.deviceId===deviceId)&&(!query||(i.summary+' '+i.source+' '+new Date(i.at).toLocaleString()).toLowerCase().includes(query.toLowerCase())));
 const viewed=selected??(deviceId?events[0]:undefined);
 function select(item:Item){setLive(false);setSelectedId(item.id);setFrame(0);setNotice(null)}
 function back(){if(live){setLive(false);return}if(selectedId){setSelectedId('');setFrame(0)}else{setDeviceId('');setQuery('')}}
 async function startPairing(){try{const r=await fetch('/api/v1/tv/pair',{method:'POST',headers:{'Content-Type':'application/json'},body:JSON.stringify({name:'Fire TV display'})});if(!r.ok)throw Error('Pairing unavailable');setPair(await r.json());setError('')}catch{setError('Pairing unavailable. Try again.')}}
 useEffect(()=>{setOrigin(window.location.origin);pendingEvent.current=new URLSearchParams(window.location.search).get('event');const fragment=new URLSearchParams(window.location.hash.slice(1)),value=fragment.get('token')||sessionStorage.getItem('smartdetector-tv')||'';if(fragment.has('token'))history.replaceState(null,'',window.location.pathname);setToken(value);if(value)sessionStorage.setItem('smartdetector-tv',value)},[]);
 useEffect(()=>{if(!pair||token)return;const timer=setInterval(async()=>{if(Date.now()>=pair.expiresAt){setPair(null);setError('Code expired. Request a new code.');return}try{const r=await fetch('/api/v1/tv/pair',{method:'POST',headers:{'Content-Type':'application/json'},body:JSON.stringify({deviceCode:pair.deviceCode})});const v=await r.json();if(v.token){sessionStorage.setItem('smartdetector-tv',v.token);setToken(v.token);setPair(null);setError('')}}catch{setError('Waiting for service connection…')}},5000);return()=>clearInterval(timer)},[pair,token]);
 const refresh=useCallback(async()=>{if(!token||document.hidden||loading.current)return;loading.current=true;try{const r=await fetch('/api/v1/tv/feed',{headers:{Authorization:'Bearer '+token},cache:'no-store',signal:AbortSignal.timeout(15000)});if(!r.ok){if(r.status===401){sessionStorage.removeItem('smartdetector-tv');setToken('');setFeed(null);setSelectedId('');setDeviceId('');throw Error('Display access expired or revoked. Pair this display again.')}throw Error('Feed unavailable. Retrying automatically.')}setFeed(await r.json());setError('')}catch(e){setError(e instanceof Error?e.message:'Feed unavailable; retrying automatically.')}finally{loading.current=false}},[token]);
 useEffect(()=>{void refresh();const timer=setInterval(()=>void refresh(),5000),wake=()=>void refresh();document.addEventListener('visibilitychange',wake);window.addEventListener('focus',wake);return()=>{clearInterval(timer);document.removeEventListener('visibilitychange',wake);window.removeEventListener('focus',wake)}},[refresh]);
 useEffect(()=>{if(!feed)return;setSelectedId(id=>feed.incidents.some(i=>i.id===id)?id:'');if(pendingEvent.current&&feed.incidents.some(i=>i.id===pendingEvent.current)){setSelectedId(pendingEvent.current);pendingEvent.current=null}if(seen.current&&alerts){const fresh=feed.incidents.find(i=>!seen.current!.has(i.id));if(fresh)setNotice(fresh)}seen.current=new Set(feed.incidents.map(i=>i.id));setNotice(n=>n&&feed.incidents.some(i=>i.id===n.id)?n:null)},[feed,alerts]);
 useEffect(()=>{if(!notice)return;const t=setTimeout(()=>setNotice(null),15000);return()=>clearTimeout(t)},[notice]);
 useEffect(()=>{root.current?.querySelector<HTMLElement>('button')?.focus()},[token,selectedId,deviceId]);
 useEffect(()=>{const handle=(e:KeyboardEvent)=>{if(e.target instanceof HTMLInputElement)return;if(['Escape','BrowserBack','Backspace'].includes(e.key)||e.keyCode===461){e.preventDefault();if(live){setLive(false)}else if(selectedId){setSelectedId('');setFrame(0)}else{setDeviceId('');setQuery('')}return}if(!['ArrowUp','ArrowDown','ArrowLeft','ArrowRight'].includes(e.key))return;const buttons=Array.from(root.current?.querySelectorAll<HTMLElement>('button,input')??[]);if(!buttons.length)return;e.preventDefault();const i=buttons.indexOf(document.activeElement as HTMLElement),step=['ArrowUp','ArrowLeft'].includes(e.key)?-1:1;buttons[(i+step+buttons.length)%buttons.length].focus()};window.addEventListener('keydown',handle);return()=>window.removeEventListener('keydown',handle)},[selectedId,live]);
 function disconnect(){setLive(false);sessionStorage.removeItem('smartdetector-tv');setToken('');setFeed(null);setSelectedId('');setDeviceId('');setNotice(null);setPair(null);seen.current=null}
 function eventCard(i:Item){return <button className="tv-card" key={i.id} onClick={()=>select(i)}>{i.thumbnail?<DetectionImage src={i.thumbnail} alt="Event preview" detections={i.frames?.[0]?.detections} compact/>:<div className="tv-placeholder">No retained image</div>}<div className="tv-card-body"><span className="tv-eyebrow">{feed?.devices.find(d=>d.id===i.deviceId)?.name??i.source} · {i.state}</span><h2>{i.summary}</h2><small>{new Date(i.at).toLocaleString()}</small><span className="tv-card-action">Review event →</span></div></button>}
 return <div className="tv-app" ref={root}><header className="tv-header"><div><Brand/><span className="tv-eyebrow">SmartDetector Console</span></div>{token&&<nav aria-label="Display controls"><button onClick={()=>{setLive(false);setSelectedId('');setDeviceId('');setQuery('')}}>Security center</button><button aria-pressed={alerts} onClick={()=>{setAlerts(!alerts);setNotice(null)}}>Alerts {alerts?'on':'off'}</button><button onClick={()=>void refresh()}>Refresh</button><button onClick={disconnect}>Disconnect</button></nav>}</header>
 {!token?<section className="tv-connect"><span className="tv-eyebrow">Your devices. One perspective.</span><h1>Connect your SmartDetector Console</h1><p>Review your location’s cataloged evidence and AI context on the big screen.</p><ol><li>On your phone or computer, sign in at <strong className="tv-url">{origin}/tv/connect</strong>.</li><li>Select Get pairing code, then enter that code on your phone.</li><li>Confirm your TV and location. This screen updates automatically.</li></ol>{pair?<div className="tv-code"><strong>{pair.userCode}</strong><p>Waiting for approval · expires in ten minutes</p></div>:<button className="tv-primary" onClick={()=>void startPairing()}>Get pairing code</button>}<p className="tv-muted">Read-only display. No password or API key is entered on the TV.</p></section>:<>
 <section className="tv-heading"><span className="tv-eyebrow">Your security journal</span><h1>{device?.name??(selected?'Event review':'Your location, in perspective.')}</h1><p>Selected evidence. AI context. A clearer record when you need to review what happened.</p><p className="tv-muted" role="status">{feed?'Feed updated '+new Date(feed.updatedAt).toLocaleTimeString():'Connecting to event feed…'} · refreshes every five seconds</p></section>
 {(deviceId||selectedId)&&<button className="tv-primary mb-4" onClick={back}>{selectedId?'← Back to '+(device?'device':'security center'):'← Back to security center'}</button>}
 {!selectedId&&!deviceId&&<><section className="tv-stats"><div><strong>{feed?.devices.length??0}</strong><span>Connected devices</span></div><div><strong>{feed?.incidents.length??0}</strong><span>Recent events</span></div><div><strong>{error?'Retrying':feed?'Connected':'Connecting…'}</strong><span>Read-only location feed</span></div></section><h2 className="tv-section-title">Devices</h2><section className="tv-grid" aria-label="Connected devices">{feed?.devices.map(d=>{const latest=feed.incidents.find(i=>i.deviceId===d.id);return <button className="tv-card" key={d.id} onClick={()=>{setLive(false);setDeviceId(d.id);setSelectedId('');setFrame(0);setQuery('')}}>{latest?.thumbnail?<DetectionImage src={latest.thumbnail} alt={'Latest saved event from '+d.name} detections={latest.frames?.[0]?.detections} compact/>:<div className="tv-placeholder">No saved event image</div>}<div className="tv-card-body"><h2>{d.name}</h2><span>{d.status} · Browse device history →</span></div></button>})}</section></>}
 {deviceId&&device?.liveView&&<button className="tv-primary mb-4" onClick={()=>setLive(!live)}>{live?'Close live view':'Live view'}</button>}
 {live&&device&&<LiveCamera key={device.id} id={device.id} token={token}/>}
 {!live&&(selected||deviceId)&&<section className="tv-detail"><div className="tv-detail-media">{viewed?.thumbnail?<DetectionImage alt="Selected event frame" src={viewed.frames?.[frame]?.preview??viewed.thumbnail} detections={viewed.frames?.[frame]?.detections}/>:<div className="tv-placeholder">No saved evidence for this device</div>}{!!viewed?.frames?.length&&<div className="tv-frame-strip" aria-label="Sampled frames">{viewed.frames.map((f,i)=><button key={i} aria-label={'Show frame '+(i+1)} aria-pressed={i===frame} onClick={()=>setFrame(i)}><img src={f.preview} alt=""/><span>{(f.at_ms/1000).toFixed(1)}s</span></button>)}</div>}</div><div><span className="tv-eyebrow">{viewed?.source??device?.status} · saved evidence</span><h2>{viewed?.summary??'Waiting for the first event'}</h2>{viewed&&<p>{new Date(viewed.at).toLocaleString()} · {viewed.state}</p>}<p className="tv-advisory">Sampled images, not continuous video. Green boxes: detector output. Dashed amber: advisory AI grounding, not a confirmed threat.</p>{selected&&!deviceId&&<button className="tv-primary" onClick={()=>{setDeviceId(selected.deviceId);setSelectedId('');setFrame(0)}}>Browse this device’s events</button>}</div></section>}
 {!selectedId&&<><div className="tv-history-heading"><h2 className="tv-section-title">{device?'Device history':'Recent events'}</h2><input className="form-control" type="search" aria-label="Search saved events" placeholder="Search saved events…" value={query} onChange={e=>setQuery(e.target.value)}/></div><p className="tv-muted">Browsing the 50 most recent saved events for this location.</p><section className="tv-grid">{events.map(eventCard)}</section>{feed&&!events.length&&<p>No matching saved events. New activity will appear automatically.</p>}</>}</>}
 {notice&&<aside className="tv-notification" aria-label="New event notification"><div role="status"><span className="tv-eyebrow">New detected event</span><h2>{notice.summary}</h2></div><button className="tv-primary" onClick={()=>select(notice)}>Review event</button><button onClick={()=>setNotice(null)}>Dismiss</button></aside>}
 {error&&<p className="tv-error" role="alert">{error}</p>}<footer>SmartDetector Console · Use remote arrows and Select. Back returns to the previous view.<br/>Notifications appear while this console is open. Stored evidence can be cleared in Settings.</footer></div>;
}
