'use client';
import {useEffect,useState} from 'react';
export default function Vision(){
 const [url,setUrl]=useState('https://autovision.dev'),[apiKey,setApiKey]=useState(''),[configured,setConfigured]=useState(false),[busy,setBusy]=useState(false),[message,setMessage]=useState(''),[persistent,setPersistent]=useState(true);
 useEffect(()=>{let active=true;fetch('/api/v1/integrations/autovision').then(r=>r.ok?r.json():Promise.reject()).then(v=>{if(active){setUrl(v.url);setConfigured(v.configured);setPersistent(v.persistent)}}).catch(()=>{if(active)setMessage('Root access required or service status unavailable')});return()=>{active=false}},[]);
 async function save(){setBusy(true);setMessage('');try{const r=await fetch('/api/v1/integrations/autovision',{method:'POST',headers:{'Content-Type':'application/json'},body:JSON.stringify({url,apiKey})});if(!r.ok)throw Error('Unable to save service configuration');setConfigured(true);setApiKey('');setMessage('Installation-wide configuration saved. Web and worker requests use it automatically.')}catch(e){setMessage(e instanceof Error?e.message:'Unable to save')}finally{setBusy(false)}}
 async function test(){setBusy(true);try{const r=await fetch('/api/v1/vision',{method:'POST',headers:{'Content-Type':'application/json'},body:JSON.stringify({demo:true,device_id:'demo-camera'})});setMessage((r.ok?'Test succeeded. ':'Test failed. ')+JSON.stringify(await r.json(),null,2))}catch{setMessage('Service unavailable')}finally{setBusy(false)}}
 return <section className="card g-card mb-4"><div className="vstack gap-3"><h2 className="h4">AutoVision system service</h2><ol><li>Sign in to <a href="https://autovision.dev" target="_blank" rel="noreferrer">AutoVision ↗</a> and create a dedicated SmartDetector service API key in Settings → API keys.</li><li>Enter the service origin and key below. Use an HTTPS origin, not an API endpoint path.</li><li>Save, then test image detection. This synthetic test may create simulated activity and use your API quota.</li></ol><span className="badge text-bg-light align-self-start">{configured?'API key configured':'API key required'}</span>{!persistent&&<p className="alert alert-warning">No persistent database configured. Admin changes last only for this server process; configure DynamoDB before production use.</p>}<form className="vstack gap-3" onSubmit={e=>{e.preventDefault();void save()}}><label>Service URL<input className="form-control" type="url" required value={url} onChange={e=>setUrl(e.target.value)} disabled={busy}/></label><label>AutoVision API key<input className="form-control" type="password" autoComplete="new-password" value={apiKey} onChange={e=>setApiKey(e.target.value)} placeholder={configured?'Leave blank to keep saved key':'Paste dedicated service key'} disabled={busy} required={!configured}/></label><p className="small mb-0">Root-only and installation-wide. Keys are encrypted server-side and never returned to the browser. Deployment values are a fallback until an admin setting is saved.</p><button className="btn btn-primary align-self-start" disabled={busy}>{busy?'Working…':'Save service settings'}</button></form><button className="btn btn-outline-primary align-self-start" disabled={!configured||busy} onClick={()=>void test()}>Test image detection</button>{message&&<pre className="mb-0" role="status">{message}</pre>}</div></section>;
}

