'use client';
import {useEffect,useState} from 'react';
import Drawer,{DrawerBackdrop} from '../drawer';
export default function Privacy(){
 const [location,setLocation]=useState<{locationId:string;locationName:string}|null>(null),[open,setOpen]=useState(false),[text,setText]=useState(''),[busy,setBusy]=useState(false),[message,setMessage]=useState(''),[error,setError]=useState('');
 useEffect(()=>{const c=new AbortController();fetch('/api/v1/privacy/history',{signal:c.signal}).then(async r=>{if(r.ok)setLocation(await r.json())}).catch(()=>{});return()=>c.abort()},[]);
 async function purge(){if(!location)return;setBusy(true);setError('');try{const r=await fetch('/api/v1/privacy/history',{method:'DELETE',headers:{'Content-Type':'application/json'},body:JSON.stringify({...location,confirmation:text})}),v=await r.json();if(!r.ok)throw Error(v.error);setOpen(false);setText('');setMessage('Saved history cleared for '+location.locationName+'. Devices remain connected and new events continue normally.')}catch(e){setError(e instanceof Error?e.message:'Unable to clear history')}finally{setBusy(false)}}
 if(!location)return null;
 return <><section className="card g-card"><h2>Privacy & saved history</h2><p>Delete saved events, AI observations, and image previews for <strong>{location.locationName}</strong>. Devices, connections, API keys, users, and plans stay unchanged. New events continue to arrive.</p><p className="small text-muted">Deletes SmartDetector’s copies only—not Ring recordings, separate AutoVision analysis jobs, third-party notifications, or deployment backups.</p><button className="btn btn-outline-danger align-self-start" onClick={()=>{setText('');setError('');setOpen(true)}}>Purge saved data</button>{message&&<p className="alert alert-success mt-3 mb-0" role="status">{message}</p>}</section><DrawerBackdrop open={open} onClose={()=>{if(!busy)setOpen(false)}}/><Drawer open={open} onClose={()=>{if(!busy)setOpen(false)}} title="Purge saved data"><p>Permanently remove saved events and images up to the moment you confirm, for <strong>{location.locationName}</strong> only. Other locations are unaffected.</p><p>This cannot be undone in SmartDetector. New events keep arriving and devices remain connected.</p><label className="form-label" htmlFor="confirm-history">Type DELETE HISTORY to confirm</label><input id="confirm-history" className="form-control mb-3" autoComplete="off" value={text} onChange={e=>setText(e.target.value)} disabled={busy}/>{error&&<p className="alert alert-danger" role="alert">{error}</p>}<div className="d-flex gap-2"><button className="btn btn-danger" disabled={busy||text!=='DELETE HISTORY'} onClick={()=>void purge()}>{busy?'Clearing…':'Permanently purge saved data'}</button><button className="btn btn-outline-secondary" disabled={busy} onClick={()=>setOpen(false)}>Cancel</button></div></Drawer></>;
}
